### PR TITLE
Make it possible to subclass wasm C++ API classes for the implementor.

### LINKED ISSUE #119: C++ opaque handle implementation is based on undefined behaviour
[basic.lval/11](http://eel.is/c++draft/expr#basic.lval-11):

> If a program attempts to access the stored value of an object through a glvalue whose type is not similar ([conv.qual]) to one of the following types the behavior is undefined:52
> 
> - the dynamic type of the object,
> - a type that is the signed or unsigned type corresponding to the dynamic type of the object, or
> - a char, unsigned char, or std​::​byte type.

The implementation of opaque handles dynamically allocates an object of one type and casts it to an unrelated type. Accessing the object through a pointer to one of the API types (e.g. in order to call `copy` or `kind`) is then undefined behaviour.

Is there documentation somewhere which outlines the use of this strategy as opposed to inheritence- or composition-based ones which don't break this rule? I realise that it may work on compilers which this has been tested with, but it seems somewhat risky to mandate UB through the interface, as implementations may change, or this may trigger sanitizer fails.

### PR DESCRIPTION
**Pull request by nlewycky**
Fixes #119.

### CODE REVIEW

File: include/wasm.hh [hunk 1]
```diff
@@ -689,11 +768,14 @@ public:
...
-  Table() = delete;
-  ~Table();
+  friend class Destroyer<Table>;
+  void destroy();
+
+protected:
+  Table() = default;
+  ~Table() = default;
 
-  using size_t = uint32_t;
```
Comment (rossberg) [inline include/wasm.hh:696]: Ah, Table::size_t is not the same as C's size_t type. So removing this typedef is incorrect. If we think reusing the canonical type name is confusing, we should find a better name.

File: src/wasm-v8.cc [hunk 2]
```diff
@@ -423,19 +385,12 @@ class StoreImpl {
...
-
-void Store::operator delete(void *p) {
-  ::operator delete(p);
+void Store::destroy() {
+  delete static_cast<StoreImpl*>(this);
 }
 
 auto Store::make(Engine*) -> own<Store> {
-  auto store = make_own(new(std::nothrow) StoreImpl());
+  auto store = std::unique_ptr<StoreImpl>(new(std::nothrow) StoreImpl());
```
Comment (rossberg) [inline src/wasm-v8.cc:393]:
```suggestion
  auto store = make_own(new(std::nothrow) StoreImpl());
```

File: src/wasm-v8.cc [hunk 3]
```diff
@@ -576,62 +531,62 @@ auto ValType::make(ValKind k) -> own<ValType> {
...
 auto ValType::kind() const -> ValKind {
-  return impl(this)->kind;
+  return ValTypeImpl::from(this)->kind;
 }
 
 
 // Extern Types
 
-struct ExternTypeImpl {
+struct ExternTypeKind {
```
Comment (rossberg) [inline src/wasm-v8.cc:549]: I'm confused, why do we need this aux wrapper?

File: src/wasm-v8.cc [hunk 4]
```diff
@@ -541,13 +496,16 @@ auto Store::make(Engine*) -> own<Store> {
...
-struct ValTypeImpl {
+struct ValTypeImpl : public ValType {
   ValKind kind;
 
   ValTypeImpl(ValKind kind) : kind(kind) {}
-};
+  ~ValTypeImpl() { stats.free(Stats::VALTYPE, this); }
 
-template<> struct implement<ValType> { using type = ValTypeImpl; };
+  static const ValTypeImpl* from(const ValType* valtype) {
```
Comment (rossberg) [inline src/wasm-v8.cc:505]: Is it not possible to keep the template programming to make the conversions regular and reduce boilerplate defs like this?

File: src/wasm-v8.cc [hunk 5]
```diff
@@ -240,30 +217,22 @@ DEFINE_VEC(Val, vec, VAL)
 
 // Configuration
 
-struct ConfigImpl {
+struct ConfigImpl : public Config {
```
Comment (rossberg) [inline src/wasm-v8.cc:220]: Let's either convert all these definitions to `class` or drop the `public`.

File: src/wasm-v8.cc [hunk 6]
```diff
@@ -532,7 +487,7 @@ auto Store::make(Engine*) -> own<Store> {
   store->context()->Enter();
   isolate->SetData(0, store.get());
 
-  return make_own(seal<Store>(store.release()));
+  return make_own<Store>(store.release());
```
Comment (rossberg) [inline src/wasm-v8.cc:490]:
```suggestion
  return own<Store>(store.release());
```

File: src/wasm-v8.cc [hunk 7]
```diff
@@ -642,16 +597,16 @@ struct FuncTypeImpl : ExternTypeImpl {
   }
 };
 
-template<> struct implement<FuncType> { using type = FuncTypeImpl; };
+static_assert(std::is_standard_layout<ExternTypeImpl<FuncTypeImpl, FuncType, ExternKind::FUNC>>::value);
```
Comment (rossberg) [inline src/wasm-v8.cc:600]: Why are these assertions needed? Can they be avoided somehow?

File: src/wasm-v8.cc [hunk 8]
```diff
@@ -1028,19 +953,20 @@ auto memorytype_to_v8(
...
+  template<typename T = Ref>
+  static auto make(StoreImpl* store, v8::Local<v8::Object> obj) -> own<T> {
     static_assert(sizeof(RefImpl) == sizeof(v8::Persistent<v8::Object>),
       "incompatible object layout");
     auto self = static_cast<RefImpl*>(store->make_handle());
     if (!self) return nullptr;
     self->Reset(store->isolate(), obj);
     stats.make(Stats::categorize(*self), self);
-    return make_own(seal<Ref>(self));
+    return make_own<T>(self);
```
Comment (rossberg) [inline src/wasm-v8.cc:969]:
```suggestion
    return own<T>(self);
```

File: include/wasm.hh [hunk 9]
```diff
@@ -180,24 +180,37 @@ public:
...
+};
+
+template<class T> using own = std::unique_ptr<T, Destroyer<T>>;
 template<class T> using ownvec = vec<own<T>>;
 
 template<class T>
 auto make_own(T* x) -> own<T> { return own<T>(x); }
 
+template<class To, class From>
+auto own_cast(own<From> x) -> own<To> { return make_own<To>(x.release()); }
```
Comment (rossberg) [inline include/wasm.hh:198]:
```suggestion
auto own_cast(own<From> x) -> own<To> { return own<To>(x.release()); }
```

File: include/wasm.hh [hunk 10]
```diff
@@ -180,24 +180,37 @@ public:
 
 // Ownership
 
-template<class T> using own = std::unique_ptr<T>;
+template <typename T>
+class Destroyer {
```
Comment (rossberg) [inline include/wasm.hh:184]:
```suggestion
class destroyer {
```
(Keep upper-case names for domain types.)

**Review by rossberg — COMMENTED** [review]
Excellent, thanks a lot! The two main questions I have are:

* Is there really no convenient way to allow implicit casting from `own<Derived>` to `own<Base>` anymore? What is common C++ practice to work around that?

* Can we somehow maintain the former regularity and brevity of going from an interface type to its implementation?

File: include/wasm.hh (hunk 1 above)
Comment (nlewycky) [reply include/wasm.hh:696]: Removing this was just a mistake on my part.

File: include/wasm.hh (hunk 9 above)
Comment (nlewycky) [reply include/wasm.hh:198]: Why does `make_own` exist? I noticed that wasm-v8.cc uses `own<T>` directly and mimicked that in my changes, but in wasm.hh I thought that making perhaps a pointer should go through the make function.

Is it supposed to be a parallel to `std::make_unique`? make_unique doesn't take a pointer, it takes the arguments that the T's c'tor would take and forwards them along. This wouldn't be useful to V8 because wasm-v8.cc uses `new(std::nothrow)` instead of regular `new`.

File: include/wasm.hh (hunk 10 above)
Comment (nlewycky) [reply include/wasm.hh]: Done.

**Comment by nlewycky** [comment]
> Excellent, thanks a lot! The two main questions I have are:
> 
> * Is there really no convenient way to allow implicit casting from `own<Derived>` to `own<Base>` anymore? What is common C++ practice to work around that?

Ordinarily you simply make the `Base` destructor `virtual` and everything just works. Deletion of a pointer at any type in the hierarchy goes through virtual method dispatch to find the most derived type's destructor.

The trouble with a non-virtual d'tor is that you can, with no complaint from the compiler, create a `unique_ptr<Derived>` cast it to a `unique_ptr<Base>`. In practical terms this means that any additional members `Derived` adds which have user-defined d'tors won't see their d'tors called. In theory, the incorrect destruction is UB regardless.

I've been assuming we can't use `virtual`, without really questioning why. This would all be a lot easier if we could use virtual dispatch and virtual inheritance.

Now, `unique_ptr<T1, D1>` can cast to `unique_ptr<T2, D2>` when `T2` is a `T1` and `D2` is a `D1`. We could use a single D type if it knew how to delete each of T1, T2, etc. So I suppose we can change `destroyer<>` to:

```
class destroyer {
public:
  template<typename T>
  void operator()(T *ptr) {
    ptr->destroy();
  }
};
```

Yep, I'll commit that.

> * Can we somehow maintain the former regularity and brevity of going from an interface type to its implementation?

Yep! Sorry for the confusion, I was always planning to put that back. That's part of the reason this was a draft PR.

`ExternType` is a little more complicated but I think I can make `impl(ptr)` work on those too, but the template code will be a little bit more than just defining a single type alias.

File: src/wasm-v8.cc (hunk 5 above)
Comment (nlewycky) [reply src/wasm-v8.cc:232]: Dropping `public` breaks a lot, I've opted for making them classes.

File: src/wasm-v8.cc (hunk 6 above)
Comment (nlewycky) [reply src/wasm-v8.cc]: I've removed make_own entirely. This line no longer needs a cast at all.

File: src/wasm-v8.cc (hunk 7 above)
Comment (nlewycky) [reply src/wasm-v8.cc:616]: Of course asserts are just that, their only purpose is to sometimes make the build fail, so they can be removed. But in this case they're indicating something very important.

Recall my original plan was `Config::method()` can safely cast `Config*` to `ConfigImpl*` because the only way to get a `Config*` is through `Config::make()` which always actually creates a `ConfigImpl`?

`ExternType` is the base of a type hierarchy. In C++ when you create an object, it starts by creating the base object first, so that's a second way to create `ExternType`. This means that when you see an `ExternType*` you don't know whether it's an `ExternTypeImpl*` or a casted `FuncType*`. Oops. How do you implement ExternType::methods()?

The obvious fix of saying "well, `FuncTypImpl` derives from `ExternTypeImpl` too" doesn't work either because now you have two distinct copies of `ExternType`, and a given `ExternType*` might be the one that's a base of `FuncType` of `FuncTypeImpl` or the one that's a base of `ExternTypeImpl` of `FuncTypeImpl`. Two copies of a base objects usually have to have distinct addresses (C++20 adds an attribute for this but it's a suggestion).

Quick aside, there's a common C++ fix for this: virtual inheritance. When inheriting virtually, you merge two copies of a base into one copy. Tada! But I'm continuing to assume we can't use virtual.

So here's what I'm going to do: we add a simple `struct ExternTypeKind` that allows us to tell what the most-derived type of the object is. Once we know that, we're home free because we know what to cast to. Now, we need to be able to go from `ExternType*` or `FuncType*` etc. to the `ExternTypeKind*` even though we don't know what casts have been performed previously. The standard term for this is _pointer-interconvertible_ and it will allow us to use `reinterpret_cast` to correctly cast between them. `ExternTypeImpl` exists to follow those rules, one of which is being a standard-layout type. That's what the static assert is checking.

Then we can derive `FuncTypeImpl` on top, and that can do whatever it likes including things which cause static_cast<> between `FuncTypeImpl` and `ExternType` to have a pointer adjustment.

Reference: https://eel.is/c++draft/basic.compound#4.3 . Also since it doesn't link to "standard-layout class": https://eel.is/c++draft/class.prop#3

File: src/wasm-v8.cc (hunk 4 above)
Comment (nlewycky) [reply src/wasm-v8.cc]: Fixed.

File: src/wasm-v8.cc (hunk 3 above)
Comment (nlewycky) [reply src/wasm-v8.cc:568]: I wrote the answer in response to a different comment: https://github.com/WebAssembly/wasm-c-api/pull/161#discussion_r520960347

File: include/wasm.hh (hunk 9 above)
Comment (nlewycky) [reply include/wasm.hh]: I've gone ahead and removed `make_own`.

File: src/wasm-v8.cc (hunk 5 above)
Comment (rossberg) [reply src/wasm-v8.cc]: > Dropping public breaks a lot, I've opted for making them classes.

I'm confused, what can it break? Isn't public simply the default for structs?

File: include/wasm.hh (hunk 9 above)
Comment (rossberg) [reply include/wasm.hh]: `make_own` exists for the same reason that `make_pair` and friends exist in the std lib: to work around C++'s odd inability to infer template arguments for constructor invocations. So this would mostly be for convenience in user code, not necessarily the implementation.

File: include/wasm.hh [hunk 11]
```diff
@@ -180,24 +180,31 @@ public:
 
 // Ownership
 
-template<class T> using own = std::unique_ptr<T>;
-template<class T> using ownvec = vec<own<T>>;
-
-template<class T>
-auto make_own(T* x) -> own<T> { return own<T>(x); }
```
Comment (rossberg) [inline include/wasm.hh:187]: I think this is still useful, see other comment.

File: src/wasm-v8.cc (hunk 3 above)
Comment (rossberg) [reply src/wasm-v8.cc:571]: So IIUC, you are saying that this (and the static_asserts) could be avoided if we used virtual inheritance on the Impl classes? As long as that does not leak to the .hh file and imposes no other overhead, I suppose I'd be fine with that.

File: src/wasm-v8.cc (hunk 5 above)
Comment (nlewycky) [reply src/wasm-v8.cc]: I'm not sure what I tested, maybe I tried `class ConfigImpl : Config` which defaults to private inheritance. `struct ConfigImpl : Config` works fine.

File: src/wasm-v8.cc [hunk 12]
```diff
@@ -1453,23 +1463,32 @@ auto Module::deserialize(Store* store_abs, const vec<byte_t>& serialized) -> own
 
 
 // TODO(v8): do better when V8 can do better.
-template<> struct implement<Shared<Module>> { using type = vec<byte_t>; };
+auto impl(Shared<Module>* x) -> vec<byte_t>* {
```
Comment (rossberg) [inline src/wasm-v8.cc:1453]: IIUC, the `implement` template no longer works for this because it requires a reinterpret_cast? Could that be fixed by introducing a SharedImpl subclass as well?

File: include/wasm.hh (hunk 9 above)
Comment (nlewycky) [reply include/wasm.hh]: Okay, but in this case it might be confusing because it's different from make_unique while otherwise own<T> is an alias to unique_ptr<T>. I've put it back, but we still don't use it in wasm-v8.

File: src/wasm-v8.cc (hunk 3 above)
Comment (nlewycky) [reply src/wasm-v8.cc:571]: No, `FuncType` etc. would need to virtually inherit from `ExternType` too. Both inheritance edges need to be marked virtual for the bases to be merged.

https://isocpp.org/wiki/faq/multiple-inheritance#virtual-inheritance-where

File: src/wasm-v8.cc (hunk 12 above)
Comment (nlewycky) [reply src/wasm-v8.cc:1453]: You'd need to make `vec<byte_t>` derive from the subclass too.

File: include/wasm.hh [hunk 13]
```diff
@@ -575,22 +630,32 @@ public:
...
-public:
-  Shared() = delete;
-  ~Shared();
-  void operator delete(void*);
+template<class T> class WASM_API_EXTERN Shared;
+
+class Module;
+
+template<>
+class WASM_API_EXTERN Shared<Module> {
```
Comment (nlewycky) [inline include/wasm.hh:638]: FYI it's possible to remove `class Module;` here by instead writing:
```
template<>
class WASM_API_EXTERN Shared<class Module> {
```
I haven't done that because I expect most users of C++ to be surprised to discover that you're allowed to write a forward declaration using an elaborated type specifier inside the template argument of an explicit specialization. Regardless, it's an option that would be a little cleaner.

File: src/wasm-v8.cc (hunk 12 above)
Comment (nlewycky) [reply src/wasm-v8.cc:1453]: No, that's not quite right. We could also have `SharedImpl` derive from both `Shared<Module>` and from `vec<byte_t>`.

Comment (nlewycky) [reply src/wasm-v8.cc]: Done. I made `SharedImpl<T>` derive from `vec<byte_t>` but when you add `SharedImpl<T != Module>` you'll probably want to make that optional.

**Review by rossberg — APPROVED** [review]
Looks good!

File: include/wasm.hh (hunk 13 above)
Comment (nlewycky) [reply include/wasm.hh:638]: `Shared<Module>` is used in the declaration of `Module`. So either we forward declare `Module` for `Shared<Module>`, or we forward-declare `Shared<Module>` for `Module`.

Comment (rossberg) [reply include/wasm.hh:638]: Ah, right. Stylistically, it probably makes more sense to define `Shared<Module>` next to `Module`, but it's a minor point.

Comment (nlewycky) [reply include/wasm.hh]: Okay, I've done what I think you mean. If that isn't exactly what you meant, it's a quick PR to fix, I'd be happy to review it.

Comment (nlewycky) [reply include/wasm.hh]: Oh, I can't merge anyways. :)

**Comment by rossberg** [comment]
Thanks a lot!
